### ISSUE TITLE
Dataset for pre-training

### ISSUE THREAD

**Issue by yamaguchiraf** [bowang-lab/AGILE#10]
Hi! Awesome job and thanks for sharing the code with us!
I would like to confirm if the chemical space of our lipids matches your pre-training virtual library.
Could you please share your SMILES data?

**Comment by rexxxx1234** [comment]
Hi @yamaguchiraf,

Thank you for your interest in our work!  We will release the pre-training library in the near future.

**Comment by yamaguchiraf** [comment]
That sounds great! Looking forward to the release of the pre-training library.
