### ISSUE TITLE
smiles of H9 and R6

### ISSUE THREAD

**Issue by lindafei01** [bowang-lab/AGILE#11]
Hi! I would like to know what are the smiles of H9 and R6.
What are the indexes of H9 and R6 in candidate_set_smiles_plus_features.csv?
Thank you!

**Comment by rexxxx1234** [comment]
Hi @lindafei01,

Sorry for the late response!

The smiles of H9 is: CCCCCCCC\C=C/CCCCCCCCNC(=O)C(CCCOC(=O)CCCCCCC)NN1CCCCC1
The smiles of R6 is: CCCCCCCCCCCCCCCC(NCCCN(CC)CC)C(=O)NCCCCCCCCCCC
