### ISSUE TITLE
Wrong fragment B9 in Figure 2b?

### ISSUE THREAD

**Issue by linkerst** [bowang-lab/AGILE#13]
Again, congratulations to you work.

In the finetuning dataset I found lipids with two double bonds in their aliphatic tail (e.g. "CCCCCCCCCCCCCCCCNC(=O)C(CCCCCOC(=O)CCCCCCC\C=C/C\C=C/CCCCC)NCCN1CCNCC1", a screenshot is added below). However, in Figure 2b of the preprint there is no such fragment in R2. Could it be that you are showing the wrong fragment in B9 and the true fragment is O=C(CCCCCCC/C=C\C/C=C\CCCCC)OCCCCCC=O ?

Thanks a lot for your answer,
Stephanie 

<img width="267" alt="Screenshot 2023-12-19 at 15 19 19" src="https://github.com/bowang-lab/AGILE/assets/20622318/8ffbc914-c1d5-47da-bb3b-8ea25932915a">

**Comment by rexxxx1234** [comment]
Hi @linkerst, thanks for the good catch!

To enhance the chemical diversity, we ultimately substituted B9 with a tail featuring two unsaturated bonds. Although the fine-tuning process furnished the appropriate dataset, there was an oversight in updating the corresponding figure.

We will revise the figure later on. Thank you again!
