### ISSUE TITLE
parameters used in pretraining

### ISSUE THREAD

**Issue by yuchanpei** [bowang-lab/AGILE#17]
Hi AGILE team,

According to the manual you provided, we have cloned the MolCLR model into the `.ckpt` folder using the command `git clone https://github.com/yuyangw/MolCLR.git`, and its contents are shown in the figure below. Would any further operations be required for the cloned files? Additionally, in the pre-training config file, should `load_model` be set to MolCLR, such as `load_model: MolCLR # resume training` ?
![image](https://github.com/user-attachments/assets/f3dd611a-5e7d-4e32-85b1-bf60fe5a6568)

Appreciate your help,
ycpei

peiyuchan@nibs.ac.cn

**Comment by rexxxx1234** [comment]
Hi @yuchanpei,

Sorry for the late reply! For the pre-training, you should only download the MolCLR checkpoints in the `.ckpt` folder, instead of clone the whole MolCLR repo. Let me know if you still have problems starting the pre-training!
