### ISSUE TITLE
"config_finetune_ori.yaml"

### ISSUE THREAD

**Issue by wklix** [bowang-lab/AGILE#3]
I want to run infer_viz.py to eval and visualize, but I couldn't find "config_finetune_ori.yaml" .  Would you please provide the  "config_finetune_ori.yaml" to run infer_viz.py.

**Comment by rexxxx1234** [comment]
Hi, thanks for pointing it out. I have cleaned up the infer_viz.py and added the instructions for running inference in the README. Let me know if you encounter any problems running it.

**Comment by wklix** [comment]
Thank you for your modifications to the infer_viz.py. By running infer_viz.py, I noticed a significant difference between the predictions and corresponding labels in the generated preds_on_lnp_hela_with_feat.csv file. Does this indicate that the fine-tuned model performs poorly? Additionally, I would like to know how to run your code to achieve the selection of the final candidate set of 15 LNPs.
