### ISSUE TITLE
how long will AGILE cost to finish the whole training?

### ISSUE THREAD

**Issue by Lee-Junyong** [bowang-lab/AGILE#4]
I am a undergraduate student in college without good GPUs to run this model.So i want to know how long AGILE will cost to finish the whole training stage and get the results?

**Comment by rexxxx1234** [comment]
Hi @Lee-Junyong, the training time will depend on the amount of data you have and the hardware. For our pre-training on 60k molecules on GPU, it takes a few hours. The fine-tuning on 12k molecules takes a few minutes.
