### ISSUE TITLE
How to finetune AND predict on new data (non cell line)

### ISSUE THREAD

**Issue by jessielyons** [bowang-lab/AGILE#8]
Hello,

We are trying to figure out how we can use your model trained on 60k compounds to finetune using our dataset? Our dataset comprises of smiles and expression from mouse experiment.

> python finetune.py config_finetune.yaml

1. Please help us understand the meaning of fine tuning and can we use your model to fine tune on a non-cell line data?
2. What is the purpose of "python infer_vis.py <folder name of the fine-tuned model>". What is this doing and if the purpose is to make predictions, how do we input our own dataset and what would be the input data requirements?

Thanks,
JL

**Comment by rexxxx1234** [comment]
Hi @jessielyons, thank you for your interest in our work! 

1, Fine-tuning in the context of machine learning is the process of taking a pre-trained model (in this case, a model trained on 60k compounds) and further training it on a new, typically smaller, dataset. This is often done to adapt the model to a specific task or domain without having to train a model from scratch, which can be time-consuming and require a lot of computational resources. The pre-trained model has already learned a set of features that are potentially useful across tasks, and fine-tuning allows it to adjust those features to the nuances of your specific data.

For your dataset of SMILES (Simplified Molecular Input Line Entry System) strings and expression data from mouse experiments, you can indeed use fine-tuning.  One thing to consider is that your new dataset should be somewhat related to the data on which the original model was trained. If your mouse expression data is significantly different from the data the model was trained on, the fine-tuning might not be as effective.

2, "python infer_vis.py" is used to perform model prediction and plot the visualization for the results. To use new data, in the following command:

python infer_vis.py <folder name of the fine-tuned model>

You can modify the config yaml file in the folder of the fine-tuned model to specify the path of the new dataset. Let me know if you encounter any trouble.
