### ISSUE TITLE
code used in pretraining

### ISSUE THREAD

**Issue by jessielyons** [bowang-lab/AGILE#9]
Hi AGILE team,

1. Can you please provide your code and 60K dataset used for pre-training? At the moment only a pretrained model is provided.
2. Also what method did you use to combine fragments into valid molecules? Can this be provided as well?

Appreciate your help,
JL
jessielyons1982@gmail.com

**Comment by rexxxx1234** [comment]
Hi @jessielyons,

We have provided the pretraining code shown here: https://github.com/bowang-lab/AGILE/blob/main/pretrain.py. For the 60K dataset, we will release it in the near future. Please stay tuned for that!

We used a Ugi-based three-component reaction (3-CR) to combine fragments into valid molecules. You can check out the details in our preprint.
